version: "3.8"
services:
  database:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - "5432:5432"
    volumes:
      - ./.cache/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: main
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: sh -c "npm run db:migrate && npm start"

volumes:
  database:
    driver: local
